Ingin kelihatan menawan? Cubalah aplikasi ini!
Anda begitu cantik, tangkaplah selfie!
Hari yang melucukan! Kongsilah detik-detik gembira anda dengan rakan-rakan!
Belum lagi mencuba gaya-gaya baharu? Marilah!
Begitu banyak gaya sudah sedia! Cubalah!
Langit biru, pokok hijau, selfie!
Rakan-rakan anda tidak sabar-sabar melihat detik-detik anda yang menggembirakan!
Hei, kami mempunyai banyak penapis yang hebat~
Anda akan menjadi lebih cantik selepas mencuba aplikasi ini!
Pembantu yang terbaik untuk mengepos foto di Instagram！