¡Feliz día! ¡Vamos a sacar fotos!
Un día tan feliz, ¡saca fotos y haz collages!
Disfruta la vida, ¡disfruta sacando fotos!
La vida es genial, ¡guarda estos momentos preciosos!
¡Me encanta sacar selfies todos los días!
Me encanta sonreír, ¡me encanta sacar selfies!
¡Sonríe y hazte un selfie!
 ¡Serás aun más hermosa después de probar esta aplicación!
¡El mejor asistente para publicar fotos en Instagram!
Nuestra meta es hacerte más hermosa.